### ISSUE TITLE
Ne garder que la valeur Start éditable et éliminer la possibilité d'éditer la valeur réelle des paramètres spatiaux ?

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/MapSPAT#13]
Que penses-tu de la possibilité de ne garder que la valeur Start éditable et d'éliminer la possibilité d'éditer la valeur réelle des paramètres spatiaux ?

Par valeur réelle, j'entends celle qui se trouve par exemple juste au-dessus du cercle d'azimut.

Je pense que cela éviterait toute confusion entre les deux valeurs (Start et Réel) et que de manière générale l'interaction avec le dispositif pourrait être plus fluide, notamment lors de l'écriture des automations.

Voici ce que je propose, pour l'Azimut, mais cela pourrait s'appliquer aux autres paramètres.

- Seul Start est modifiable. La valeur réelle est visible, mais n'est pas modifiable.
- La valeur Range est de zéro par défaut. 
- Bien qu'aucun descripteur audio ne soit actif dans la matrice, en éditant Start, je modifie la valeur réelle d'Azimuth et je déplace la source (est-ce possible ?).
- La valeur Range pourrait être grisée à l'ouverture de l'appareil et devenir modifiable dès qu'un descripteur audio est activé dans la matrice. Cependant, elle pourrait aussi être toujours modifiable, comme maintenant, et elle n'aurait toujours pas d'effet sur la valeur réelle de l'azimut lorsqu'aucun descripteur n'est sélectionné.

Cela permettrait à la fois d'écrire les automations des mouvements à la main (Range = 0 ), et d'utiliser les descripteurs pour piloter le paramètre (Range pas égal à zéro).

Qu'en penses-tu ?

**Comment by jpjullin** [comment]
Je n'avais pas pensé au fait qu'on puisse déplacer la source avec la barre bleue. Ce n'est pas prévu, je pensais avoir complètement désactivé l'interaction directe sans passer par un descripteur. Je pensais qu'on ne voulait pas que les utilisateurs puissent changer la valeur réelle.

Je ne suis pas certain de comprendre. La valeur start permet de placer la source à un endroit précis si le _range_ est à 0, et en augmentant le range on peut graduellement influencer cette position avec les descripteurs.

J'ai enlevé la possibilité de changer les barres bleues dans la v1.01. Pour sauvegarder une position fixe, il faut changer _start_ ou _range_ et le sauver dans un preset. 

Est-ce que simplement ça répondrais à tes besoins?

**Comment by NicolaGiannini** [comment]
V101
En ce qui concerne mes besoins, tout fonctionne bien et je réussis à faire tout ce dont j'ai besoin. Cependant, je pense que pour quelqu'un-e qui utilise le dispositif pour la première fois, il pourrait ne pas être très intuitif que pour positionner une source sans l'effet d'un descripteur il faut activer un descripteur. Cela dit, il est toujours possible d'expliquer les étapes à suivre dans le guide sur GitHub.

Juste avant de clore la question, j'aimerais considérer une dernière fois avec toi deux alternatives :

1. Faire en sorte que "Start", même si aucun descripteur n'est sélectionné, contrôle quand même la valeur réelle. Je l'imagine comme si "Start" était mappé à un descripteur "vide" à Range zéro. Une fois qu'un descripteur est sélectionné, tout fonctionnerait comme actuellement. Cependant, je me souviens que tu avais dit que cette solution nécessiterait beaucoup de travail de programmation et pourrait introduire des bugs, donc je comprends si c'est problématique.

2. Une autre option serait d'avoir tous les paramètres spatiaux activés par défaut sur "Loudness" avec Range à zéro. Cela permettrait de manipuler immédiatement les paramètres spatiaux avec un effet sur la spatialisation. Je sais que ce n'est pas une solution très élégante, mais peut-être que je la trouve un peu plus intuitive que l'actuelle.

Sinon, si tu penses qu'il vaut mieux laisser tout tel quel, nous pourrions rendre la valeur réelle grise, pour ne pas donner l'impression qu'elle est modifiable.

Qu'en penses-tu ?

Merci beaucoup en tout cas !

**Comment by jpjullin** [comment]
v1.02
J'ai fais en sorte que si aucun descripteur n'est activé dans la matrice, _start_ change directement la position de la source. La 2e solution me paraît demander trop de modifications pour faire qu'un descripteur contrôle une position, ce qui serait je pense contre productif. 

Je pense que celle actuelle est la solution la plus clean, dis moi ce que tu en penses.

**Comment by NicolaGiannini** [comment]
v1.02

Ça me semble parfait ! 

Je me demande seulement si nous ne devrions pas changer la couleur de la valeur réelle, juste pour indiquer qu'elle ne peut pas être modifiée. Mais dans tous les cas, c'est parfait, merci !

**Comment by jpjullin** [comment]
Parfait! 

Pour l'instant je vais laisser ces couleurs, parce que sinon avec les thèmes Live il risque d'y avoir des combinaisons où le texte ne sera plus lisible.
