### ISSUE TITLE
Les valeurs spatiales et d'analyse enregistrées dans les presets ne semblent pas être rappelées correctement si on redémarre Ableton.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/MapSPAT#16]
Les valeurs spatiales et d'analyse enregistrées dans les presets ne semblent pas être rappelées correctement si on redémarre Ableton.

Etapes pour recréer le bug.

Je crée un preset 1 avec les valeurs Azimuth et Loudness. 
![Screenshot 2024-05-03 at 13 34 26](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/2c298a92-5ce0-4813-a338-4f76e23716d3)

Je crée un preset 2 en modifiant ces valeurs.

![Screenshot 2024-05-03 at 13 34 33](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/ed55a35a-f1d2-480f-ae2b-c17d6a0cf5a1)

Si je passe d'un preset à l'autre sans fermer Live, tout fonctionne.

Si je redémarre Live, le second preset semble écraser le premier. 

![Screenshot 2024-05-03 at 13 36 25](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/7283a722-9cd9-4999-a2e6-d414377af0f5)

![Screenshot 2024-05-03 at 13 36 32](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/9633c8ea-2853-44dd-958b-c2ed7e0f868b)

La valeur des presets est différente, mais les paramètres rappelés sont les mêmes.

**Comment by jpjullin** [comment]
J'ai l'impression qu'il s'agit d'un comportement non prévu de pattrstorage. Les presets fonctionnent bien tant qu'on n'ouvre pas le device, et si la dernière version du device sauvée a été faite en désactivant puis réactivant _Parameter Mode Enable_ du pattrstorage.

La dernière version en ligne est censée corriger le problème (v1.01)

**Comment by NicolaGiannini** [comment]
V101
J'ai essayé avec la V101 et j'ai toujours le même comportement. 

Je crée un preset 1 avec les valeurs Azimuth et Loudness.
![Screenshot 2024-05-05 alle 17 05 25](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/77c1a5a2-8627-4245-8e8e-eeef9d94a926)

Je crée un preset 2 en modifiant ces valeurs.

![Screenshot 2024-05-05 alle 17 05 30](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/f5e9e2a0-a4c5-42fe-a159-eb2ca7c4255b)

Si je ne ferme pas Live, tout fonctionne.

Si je redémarre Live, le second preset semble overwrite le premier.


![Screenshot 2024-05-05 alle 17 06 51](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/9a0b0eb9-b458-4976-8ce3-a451bd937d81)

![Screenshot 2024-05-05 alle 17 06 56](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/151ffb86-be6f-4a8a-9148-fa1816c33933)

**Comment by jpjullin** [comment]
Ok, note à moi-même: ne plus jamais utiliser --- dans un bpatcher de device Max4Live. Se débrouiller autrement.

La v1.02 devrait régler ce problème, dis moi si c'est ok

**Comment by NicolaGiannini** [comment]
V102
Les presets sont maintenant rappelés correctement au redémarrage de Live !

Cependant, je constate un nouveau problème à la fonction Overwrite. 

Si je modifie un preset, Store devient rouge correctement, mais si j'appuie sur Store et Ok quand on me demande si je veux Overwrite, Store redevient rouge, et MapSPAT ne me demande pas le nom sous lequel sauvegarder le preset édité, comme il le faisait auparavant. 

Si je sélectionne le preset, les valeurs avant la modification sont chargées. 


https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/33ce6657-ca09-4d2c-9678-a227f8f9595a

**Comment by jpjullin** [comment]
Hum c'est étrange, je n'arrive pas à reproduire le problème. 

J'ai freeze une nouvelle version (v1.03), peux-tu me dire si ça fonctionne mieux? Tout fonctionne comme prévu de mon côté

**Comment by NicolaGiannini** [comment]
V103
Je vois ce qui se passe !
Dans mon cas, cela semble dépendre du fait que le preset a été sauvegardé avec un nom composé de lettres ou de chiffres. Si j'enregistre avec un nom composé de lettres, ça marche, mais avec un chiffre, ça ne marche pas. 

Peux-tu vérifier si c'est aussi ton cas ? 

Si c'est trop compliqué de trouver une solution, on peut aussi simplement l'écrire dans le guide. 

https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/24faa00c-a39b-41aa-bc18-d4850fe40de2

**Comment by jpjullin** [comment]
Oh ok je n'avais pas pensé à ça! Maintenant les noms de presets peuvent être composés de chiffres uniquement. 

Merci pour le debug, c'est réglé dans la v1.04

**Comment by NicolaGiannini** [comment]
Excellent! Tout fonctionne. Merci à toi.
