### ISSUE TITLE
Presets : la sélection d'un autre descripteur audio déclenche une détection de changement (visuelle) dans le preset, même si aucune valeur n'est modifiée.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/MapSPAT#17]
Presets: la sélection d'un autre descripteur audio déclenche une détection de changement (visuelle) dans le preset, même si aucune valeur n'est modifiée. La sélection d'un autre paramètre spatial ne déclenche pas de détection de changement.

https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/66e15ce2-aee5-44fe-bb7a-4cfa66273f50

Dans la vidéo, je overwrite le preset pour l'enregistrer à nouveau. 

Je ne sais pas si cela pourrait être lié à https://github.com/GRIS-UdeM/MapSPAT/issues/16

**Comment by jpjullin** [comment]
La v1.01 corrige ce problème
