### ISSUE TITLE
Lors de la réouverture d'un projet Live, la position réelle ne suit pas la position de départ mais reste à zéro.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/MapSPAT#18]
Lors de la réouverture d'un projet Live où une position de Start a été enregistrée, la position de Start est rappelée correctement, mais la position réelle ne suit pas la position de Start, elle reste à zéro.

**Comment by jpjullin** [comment]
Corrigé dans la v1.05
