### ISSUE TITLE
Une fois qu'un nouveau preset est sauvegardé, Store devient rouge comme si le preset avait été édité. 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/MapSPAT#19]
v105

Une fois qu'une nouveau preset est sauvegardé, Store devient rouge comme si le preset avait été édité. Cela se produit lors de la création d’un nouveau preset et lors du rappel d'un preset. 

https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/95e877b5-7999-462c-893d-aa3b7b3ee6a8

**Comment by jpjullin** [comment]
Corrigé dans la v1.06

**Comment by NicolaGiannini** [comment]
V106
Maintenant, cela semble fonctionner! Le seul problème semble être avec le descripteur audio Speed. Dans ce cas, le fait d'avoir de l'audio en entrée audio semble faire détecter un changement dans le preset, même si aucun paramètre n'a été modifié. 

https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/d7d596c3-b251-4ba1-b84f-45172f40eae2

**Comment by jpjullin** [comment]
Corrigé dans la v1.07
