### ISSUE TITLE
Il semble que pour les paramètres XYZ du mode CUBE, les paramètres en degrés du mode DOME soient présents.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/MapSPAT#20]
V107

Il semble que pour les paramètres XYZ du mode CUBE, les paramètres en degrés du mode DOME soient présents.

Les paramètres X et Y du mode CUBE sont en degrés, alors qu'ils devraient être des valeurs numériques allant de -1,66 à 1,66. Il semble donc impossible de positionner des sources en mode CUBE.
![Screenshot 2024-05-15 alle 13 14 32](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/056fde2e-3614-43ea-bb16-75713c782658)

Le paramètre Z semble être vide.

Je remarque que dans la version 1.01, les paramètres pour le mode CUBE étaient corrects.

Une réflexion sur le paramètre Z. Dans la version 1.01, ce paramètre va de 0 à 1. Je le ferais probablement aller de 0 à 1,61 si possible.

J'ai remarqué que le V. Span dans la version 1.01 peut aussi aller en bas du Speaker Setup. Je pense que cela dépend de la façon dont SpaGRIS lit les données. Je me demandais s'il y avait un moyen de faire en sorte qu'il ne s'étende qu'en haut. Sinon, on le laisse tel quel, pas de problème !

![Screenshot 2024-05-15 alle 13 27 04](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/36d6c526-12bf-4071-b5a5-81aa511b0315)

**Comment by jpjullin** [comment]
Le mode cube est corrigé dans la v1.08.

Je ne suis pas certain de comprendre pourquoi tu veux que Z aille jusqu'à 1.61? Simplement pour le GUI? Dans ControlGRIS on ne peut pas aller plus loin que 1.

Pour le V.Span je ne peux malheuresement pas le changer, il faudrait gérer ça dans SpatGRIS. Mais comme les speaker setups peuvent maintenant aller sous le sol, je pense que cette fonctionnalité est prévue

**Comment by NicolaGiannini** [comment]
V108

Mode CUBE

X et Y fonctionnent.
Pour Z, Start ne semble pas modifier la valeur réelle. 

https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/0f05b8c2-9aa8-4c7c-a512-8972c065835b

Dans les dernières versions de ControlGRIS, en activant la fonction Extended top, Z peut être envoyé au-dessus (et aussi en dessous) de la configuration des haut-parleurs, afin de profiter des attenuation settings. 

https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/e94744cf-9806-44f5-8227-fe2e42a4910d


Si possible, je ferais bouger Z de 0 à 1,61 (et donc pas aussi en dessous). Sinon, si ce n'est pas possible, le fonctionnement actuel est aussi bon. 

Mode DOME

Tout semble fonctionner, mais l'affichage graphique de l'azimut et de l'élévation semble celui de X et Y.
![Screenshot 2024-05-16 alle 10 21 02](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/271a11de-b562-43f0-92a7-be321967b683)

![Screenshot 2024-05-16 alle 10 21 42](https://github.com/GRIS-UdeM/MapSPAT/assets/35705913/06a76d1d-d83f-4e2b-a2c6-d7ae0027706f)

**Comment by jpjullin** [comment]
Désolé pour ça, j'avais râté le fonctionnement du Z pour _Start_. J'ai aussi augmenté le Z pour aller de 0 à 1.61, je ne connaissais pas la fonction Extended Top.

Tout est corrigé dans la v1.09!
